swagger: "2.0"
info:
  description: "Stampede is a framework, or an eco-system written in TypeScript for Deno, made with emphasis on delivering new features quicker than ever before."
  version: "1.0.0"
  title: "Stampede"
  contact:
    email: "anurbasic01@outlook.com"
  license:
    name: "MIT License"
    url: "https://github.com/bashovski/stampede/blob/master/LICENSE"
host: "localhost:80"
tags:
  - name: "auth"
    description: "Collection of all auth requests"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/bashovski/stampede"
schemes:
  - "https"
  - "http"
paths:
  /users/register:
    post:
      tags:
        - "auth"
      summary: "Register a new user"
      description: ""
      operationId: "registerUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Registration request body/data"
          required: true
          schema:
            $ref: "#/definitions/UserRegister"
      responses:
        "400":
          description: "Bad Request"
        "201":
          description: "Successfully registered user"
  /users/login:
    post:
      tags:
        - "auth"
      summary: "Login as an existing user"
      description: ""
      operationId: "loginUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Login request body/data"
          required: true
          schema:
            $ref: "#/definitions/UserLogin"
      responses:
        "400":
          description: "Bad Request/Invalid password"
        "404":
          description: "There's no such account with passed credentials. Please sign up."
        "200":
          description: "Successfully logged in"
  /users/iam:
    get:
      tags:
        - "auth"
      summary: "Fetch current user's info"
      description: ""
      operationId: "IAM"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "401":
          description: "Unauthorized"
        "200":
          description: "Returns user info"
  /users/logout:
    delete:
      tags:
        - "auth"
      summary: "Log out the user"
      description: ""
      operationId: "logoutUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "401":
          description: "Unauthorized"
        "204":
          description: "Logout was successful"
  /users/{id}/verify:
    patch:
      tags:
        - "auth"
      summary: "Verify account"
      description: ""
      operationId: "verifyAccount"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Verification identifier"
          required: true
          type: "string"
      responses:
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Incorrect verification token"
        "200":
          description: "Account successfully verified!"
  /users/password/reset:
    patch:
      tags:
        - "auth"
      summary: "Reset user's password"
      description: ""
      operationId: "resetUserPassword"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Password reset body"
          required: true
          schema:
            $ref: "#/definitions/ResetPassword"
      responses:
        "400":
          description: "Bad Request"
        "401":
          description: "Invalid password"
        "404":
          description: "There's no account registered with this email."
        "200":
          description: "Password successfully reset."
  /users/account/recover/code:
    patch:
      tags:
        - "auth"
      summary: "Require recovery code for account recovery process"
      description: ""
      operationId: "requireRecoveryCode"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Account recovery body"
          required: true
          schema:
            $ref: "#/definitions/AccountRecoveryRequireCode"
      responses:
        "400":
          description: "Bad Request"
        "404":
          description: "There's no account registered with this email."
        "200":
          description: "Recovery code successfully sent."
  /users/account/recover:
    patch:
      tags:
        - "auth"
      summary: "Require recovery code for account recovery process"
      description: ""
      operationId: "recover"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Account recovery body"
          required: true
          schema:
            $ref: "#/definitions/AccountRecovery"
      responses:
        "400":
          description: "Bad Request"
        "404":
          description: "You have entered an invalid code."
        "200":
          description: "Successfully recovered account."
definitions:
  UserRegister:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      dateOfBirth:
        type: "string"
        format: "date-time"
  UserLogin:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  ResetPassword:
    type: "object"
    properties:
      email:
        type: "string"
      oldPassword:
        type: "string"
      newPassword:
        type: "string"
  AccountRecoveryRequireCode:
    type: "object"
    properties:
      email:
        type: "string"
  AccountRecovery:
    type: "object"
    properties:
      recoveryCode:
        type: "string"
      password:
        type: "string"
externalDocs:
  description: "Find out more about Stampede"
  url: "https://github.com/bashovski/stampede"
